# Generated by Django 4.0.4 on 2022-11-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_bodyheight_profile_bodyweight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='BodyHeight',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='BodyWeight',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='createDate',
        ),
        migrations.AlterField(
            model_name='bodyvitalslog',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bodyvitalslog',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BodyHeight',
        ),
        migrations.DeleteModel(
            name='BodyWeight',
        ),
    ]
