# Generated by Django 4.0.4 on 2022-11-02 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_bodyheight_remove_profile_bodyweight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodyvitalslog',
            name='height',
        ),
        migrations.RemoveField(
            model_name='bodyvitalslog',
            name='weight',
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bodyvitalslog',
            name='activityLevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.activitylevel'),
        ),
    ]
