# Generated by Django 3.2 on 2022-04-06 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plannerapp', '0002_alter_workout_workout_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutplan',
            old_name='weekday',
            new_name='first_day',
        ),
    ]
