# Generated by Django 3.2 on 2022-04-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannerapp', '0003_rename_weekday_workoutplan_first_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
