# Generated by Django 3.2 on 2022-04-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannerapp', '0009_alter_workout_workout_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
