# Generated by Django 3.2 on 2022-04-11 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plannerapp', '0012_alter_workout_workout_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutplan',
            options={'ordering': ['-first_day']},
        ),
    ]
