# Generated by Django 3.2 on 2022-04-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plannerapp', '0014_auto_20220411_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutplan',
            options={'ordering': ['first_day']},
        ),
    ]
