# Generated by Django 4.0.4 on 2022-10-23 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_remove_muscle_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='primaryTargetMuscles',
        ),
        migrations.AddField(
            model_name='exercise',
            name='primaryTargetMuscles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primaryTargetMuscles', to='programs.muscle'),
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='secondaryTargetMuscles',
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondaryTargetMuscles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondaryTargetMuscles', to='programs.musclegroup'),
        ),
    ]
