# Generated by Django 4.0.4 on 2022-10-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_remove_exercise_primarytargetmuscles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, default='static/image/bodydefault.png', null=True, upload_to='exercise_photos/%Y/%m/'),
        ),
    ]
