# Generated by Django 4.0.4 on 2022-11-02 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_alter_exercise_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='intervalOnly',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='primaryTargetMuscles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primaryTargetMuscles', to='programs.muscle'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='secondaryTargetMuscles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondaryTargetMuscles', to='programs.musclegroup'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
