# Generated by Django 4.0.4 on 2022-09-24 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.equipment'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='intervalOnly',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.level'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='mechanics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.exercisemechanic'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.exercisetype'),
        ),
    ]
