# Generated by Django 4.0.4 on 2022-09-25 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programs', '0006_exercise_equipment_exercise_intervalonly_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinearWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='periodization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='repType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.gender')),
                ('goal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.routinegoal')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.level')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.routinetype')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('day', models.IntegerField(null=True)),
                ('periodization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.periodization')),
                ('routineld', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.routine')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restTime', models.IntegerField(blank=True, null=True)),
                ('exerciseId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.exercise')),
                ('workoutId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.workout')),
                ('workoutTypeId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.linearworkout')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workoutExerciseİd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.workoutexercise')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExerciseSetWithReps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repCount', models.IntegerField(null=True)),
                ('repType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.reptype')),
                ('workoutExerciseSetId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.workoutexerciseset')),
            ],
        ),
        migrations.AddField(
            model_name='linearworkout',
            name='workoutId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.workout'),
        ),
        migrations.CreateModel(
            name='IntervalWorkoutExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(null=True)),
                ('workoutExerciseSetId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.workoutexerciseset')),
            ],
        ),
        migrations.CreateModel(
            name='CircularWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lapCount', models.IntegerField(null=True)),
                ('restBetweenLaps', models.IntegerField(null=True)),
                ('workoutId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.workout')),
            ],
        ),
    ]
