# Generated by Django 4.0.4 on 2022-11-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_workout_user_alter_workout_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_time_name', models.CharField(max_length=50)),
            ],
        ),
    ]
