# Generated by Django 4.0.4 on 2022-09-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_gender_linearworkout_periodization_reptype_routine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='level',
        ),
        migrations.AddField(
            model_name='routine',
            name='level',
            field=models.ManyToManyField(related_name='lev', to='programs.level'),
        ),
    ]
