# Generated by Django 4.1.3 on 2022-11-24 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_remove_workout_day_workout_beginning_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='name',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='periodization',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='routineld',
        ),
        migrations.AddField(
            model_name='workout',
            name='Muscles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Muscles', to='programs.muscle'),
        ),
    ]
