# Generated by Django 4.0.4 on 2022-10-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_workoutexercise_linkedexercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
