# Generated by Django 4.1.3 on 2022-11-24 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_remove_workout_name_remove_workout_periodization_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='periodization',
        ),
    ]
